apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: python3:v1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: myapp-pvc
          mountPath: /app/data
        - name: myapp-pvc
          mountPath: /app/new_folder

      volumes:
      - name: myapp-pvc
        persistentVolumeClaim:
          claimName: myapp-pvc
  
