apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  storageClassName: my-storage-class 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

